version: '3.7'

# Spark with Hadoop FS cluster

services:

  namenode:
    image: bde2020/hadoop-namenode:2.0.0-hadoop3.2.1-java8
    restart: always
    container_name: namenode
    ports:
      - "9000:9000"
      - "9870:9870"
    volumes:
      - hadoop_namenode:/hadoop/dfs
    env_file:
      - ./hadoop.env
    #command:
    #  ["hdfs dfs -mkdir -p /usr/local/hadoop"]
    networks:
      spark-hdfs-network:

  datanode-1:
    image: bde2020/hadoop-datanode:2.0.0-hadoop3.2.1-java8
    restart: always
    container_name: datanode-1
    ports:
      - "9864:9864"
    volumes:
      - hadoop_datanode_1:/hadoop/dfs
    environment:
      - SERVICE_PRECONDITION=namenode:9000
      - CORE_CONF_fs_defaultFS=hdfs://namenode:9000
      - HDFS_CONF_dfs_datanode_address_datanode_1=datanode-1:9864
      - HDFS_CONF_dfs_datanode_http_address_datanode_1=datanode-1:9864
    depends_on:
      - namenode
    env_file:
      - ./hadoop.env
    networks:
      spark-hdfs-network:

  datanode-2:
    image: bde2020/hadoop-datanode:2.0.0-hadoop3.2.1-java8
    restart: always
    container_name: datanode-2
    ports:
      - "9865:9864"
    volumes:
      - hadoop_datanode_2:/hadoop/dfs
    environment:
      - SERVICE_PRECONDITION=namenode:9000
      - HDFS_CONF_dfs_datanode_address_datanode_2=datanode-2:9864
      - HDFS_CONF_dfs_datanode_http_address_datanode_2=datanode-2:9864
    depends_on:
      - namenode
    env_file:
      - ./hadoop.env
    networks:
      spark-hdfs-network:

  resourcemanager:
    image: bde2020/hadoop-resourcemanager:2.0.0-hadoop3.2.1-java8
    container_name: resourcemanager
    environment:
      SERVICE_PRECONDITION: "namenode:9000 datanode-1:9864 datanode-2:9864"
    depends_on:
      - namenode
      - datanode-1
      - datanode-2
    env_file:
      - ./hadoop.env
    ports:
      - "8033:8033"
      - "8088:8088"
    networks:
      spark-hdfs-network:

  historyserver:
    image: bde2020/hadoop-historyserver:2.0.0-hadoop3.2.1-java8
    container_name: historyserver
    depends_on:
      - namenode
      - datanode-1
      - datanode-2
    volumes:
      - hadoop_historyserver:/hadoop/yarn/timeline
    environment:
      SERVICE_PRECONDITION: "namenode:9000 namenode:9870 datanode-1:9864 datanode-2:9864 resourcemanager:8088"
    env_file:
      - ./hadoop.env
    ports:
      - "8188:8188"
    networks:
      spark-hdfs-network:

  nodemanager:
    image: bde2020/hadoop-nodemanager:2.0.0-hadoop3.2.1-java8
    container_name: nodemanager
    depends_on:
      - namenode
      - datanode-1
      - datanode-2
    environment:
      SERVICE_PRECONDITION: "namenode:9000 namenode:9870 datanode-1:9864 datanode-2:9864 resourcemanager:8088"
    env_file:
      - ./hadoop.env
    ports:
      - "8042:8042"
    networks:
      spark-hdfs-network:

  spark-master:
    image: bde2020/spark-master:3.3.0-hadoop3.3
    restart: always
    container_name: spark-master
    ports:
      - "7077:7077"
      - "8080:8080"
    environment:
      - SPARK_CONF_spark_master_host=spark-master
      - SPARK_CONF_spark_eventLog_enabled=true
      - SPARK_CONF_spark_eventLog_dir=hdfs://namenode:9000/spark-eventlog
      - SPARK_CONF_spark_history_fs_logDirectory=hdfs://namenode:9000/spark-eventlog
      - SPARK_CONF_spark_history_ui_port=8188
    env_file:
      - ./hadoop.env
    depends_on:
      - namenode
    networks:
      spark-hdfs-network:

  spark-worker-1:
    image: bde2020/spark-worker:3.3.0-hadoop3.3
    container_name: spark-worker-1
    restart: always
    ports:
      - "8081:8081"
    environment:
      - SPARK_MASTER=spark://spark-master:7077
      - SPARK_CONF_spark_worker_port=8881
      - SPARK_CONF_spark_master_host=spark-master
    env_file:
      - ./hadoop.env
    depends_on:
      - namenode
      - spark-master
    networks:
      spark-hdfs-network:

  spark-worker-2:
    image: bde2020/spark-worker:3.3.0-hadoop3.3
    container_name: spark-worker-2
    restart: always
    ports:
      - "8082:8081"
    environment:
      - SPARK_MASTER=spark://spark-master:7077
      - SPARK_CONF_spark_worker_port=8081
      - SPARK_CONF_spark_master_host=spark-master
    env_file:
      - ./hadoop.env
    depends_on:
      - namenode
      - spark-master
    networks:
      spark-hdfs-network:

volumes:
  hadoop_namenode:
  hadoop_datanode_1:
  hadoop_datanode_2:
  hadoop_historyserver:

networks:
  spark-hdfs-network:
    ipam:
      config:
        - subnet: 172.16.238.0/24